- name: ptgrey.0
  fps: 5
  type: rgb
  resolution:
    width: 728
    height: 1288
- name: ptgrey.1
  fps: 5
  type: rgb
  resolution:
    width: 728
    height: 1288
- name: ptgrey.2
  fps: 5
  type: rgb
  resolution:
    width: 728
    height: 1288
- name: ptgrey.3
  fps: 5
  type: rgb
  resolution:
    width: 728
    height: 1288